<?php

namespace Database\Seeders;

use App\Models\ExploreItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExploreItemSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the explore_items table.
     */
    public function run(): void
    {
        $exploreItems = [
            ['title' => 'Goa Weekend', 'location' => 'Goa', 'country' => 'India', 'category' => 'Beach', 'duration' => '3 days', 'price_from' => '₹8,999', 'rating' => 4.7, 'hotels' => 18, 'season' => 'Oct - Mar', 'featured' => true, 'description' => 'A quick beach escape with sunsets, nightlife, and relaxed vibes.', 'image' => 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Kerala Backwater Retreat', 'location' => 'Alleppey', 'country' => 'India', 'category' => 'Nature', 'duration' => '5 days', 'price_from' => '₹16,499', 'rating' => 4.9, 'hotels' => 24, 'season' => 'Sep - Mar', 'featured' => true, 'description' => 'Houseboats, greenery, and calm backwaters for a peaceful reset.', 'image' => 'https://images.unsplash.com/photo-1516690561795-2c5c0d0c7a03?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Manali Mountain Break', 'location' => 'Manali', 'country' => 'India', 'category' => 'Hill Station', 'duration' => '4 days', 'price_from' => '₹13,499', 'rating' => 4.7, 'hotels' => 20, 'season' => 'Oct - Jun', 'featured' => false, 'description' => 'Snowy views, cafes, adventure sports, and mountain roads.', 'image' => 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Jaipur Royal Circuit', 'location' => 'Jaipur', 'country' => 'India', 'category' => 'Culture', 'duration' => '3 days', 'price_from' => '₹9,999', 'rating' => 4.6, 'hotels' => 17, 'season' => 'Oct - Mar', 'featured' => false, 'description' => 'Palaces, forts, colorful bazaars, and royal heritage.', 'image' => 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Rishikesh River Adventure', 'location' => 'Rishikesh', 'country' => 'India', 'category' => 'Adventure', 'duration' => '3 days', 'price_from' => '₹8,499', 'rating' => 4.8, 'hotels' => 15, 'season' => 'Sep - Apr', 'featured' => false, 'description' => 'River rafting, yoga, and scenic riverside stays.', 'image' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Udaipur Heritage Stay', 'location' => 'Udaipur', 'country' => 'India', 'category' => 'Heritage', 'duration' => '4 days', 'price_from' => '₹11,999', 'rating' => 4.7, 'hotels' => 16, 'season' => 'Oct - Mar', 'featured' => false, 'description' => 'Lakeside charm, royal architecture, and slow travel.', 'image' => 'https://images.unsplash.com/photo-1477586957320-9ef37e6c2120?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Munnar Tea Trail', 'location' => 'Munnar', 'country' => 'India', 'category' => 'Nature', 'duration' => '4 days', 'price_from' => '₹12,499', 'rating' => 4.8, 'hotels' => 14, 'season' => 'Sep - May', 'featured' => false, 'description' => 'Tea plantations, misty hills, and scenic drives.', 'image' => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Andaman Island Getaway', 'location' => 'Port Blair', 'country' => 'India', 'category' => 'Island', 'duration' => '5 days', 'price_from' => '₹22,999', 'rating' => 4.9, 'hotels' => 21, 'season' => 'Oct - May', 'featured' => true, 'description' => 'Clear waters, snorkeling, and island hopping.', 'image' => 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Ladakh High Pass Explorer', 'location' => 'Leh', 'country' => 'India', 'category' => 'Adventure', 'duration' => '6 days', 'price_from' => '₹24,999', 'rating' => 4.9, 'hotels' => 12, 'season' => 'May - Sep', 'featured' => true, 'description' => 'Epic roads, monasteries, and dramatic landscapes.', 'image' => 'https://images.unsplash.com/photo-1489493512162-9f3b0f1f3a3f?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Coorg Coffee Estate Escape', 'location' => 'Coorg', 'country' => 'India', 'category' => 'Nature', 'duration' => '3 days', 'price_from' => '₹10,499', 'rating' => 4.7, 'hotels' => 13, 'season' => 'Oct - Apr', 'featured' => false, 'description' => 'Coffee estates, waterfalls, and cozy stays.', 'image' => 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=900&q=80'],

            ['title' => 'Dubai City Luxury', 'location' => 'Dubai', 'country' => 'UAE', 'category' => 'Luxury', 'duration' => '4 days', 'price_from' => '$899', 'rating' => 4.8, 'hotels' => 35, 'season' => 'Nov - Mar', 'featured' => true, 'description' => 'Skyline views, luxury shopping, and desert thrills.', 'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Abu Dhabi Grand Tour', 'location' => 'Abu Dhabi', 'country' => 'UAE', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$799', 'rating' => 4.7, 'hotels' => 28, 'season' => 'Nov - Mar', 'featured' => false, 'description' => 'Culture, architecture, and theme parks.', 'image' => 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Istanbul Bosphorus Breeze', 'location' => 'Istanbul', 'country' => 'Turkey', 'category' => 'Culture', 'duration' => '5 days', 'price_from' => '$949', 'rating' => 4.8, 'hotels' => 26, 'season' => 'Apr - Nov', 'featured' => false, 'description' => 'Mosques, bazaars, and scenic cruises.', 'image' => 'https://images.unsplash.com/photo-1524231757912-21f4fe3c7d14?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Bali Paradise Reset', 'location' => 'Bali', 'country' => 'Indonesia', 'category' => 'Beach', 'duration' => '6 days', 'price_from' => '$1,250', 'rating' => 4.9, 'hotels' => 40, 'season' => 'May - Oct', 'featured' => true, 'description' => 'Villas, beaches, rice terraces, and temples.', 'image' => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Cappadocia Balloon Escape', 'location' => 'Cappadocia', 'country' => 'Turkey', 'category' => 'Romantic', 'duration' => '4 days', 'price_from' => '$1,099', 'rating' => 4.9, 'hotels' => 22, 'season' => 'Apr - Nov', 'featured' => true, 'description' => 'Hot air balloons and cave stays.', 'image' => 'https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Phuket Island Hopping', 'location' => 'Phuket', 'country' => 'Thailand', 'category' => 'Beach', 'duration' => '5 days', 'price_from' => '$899', 'rating' => 4.7, 'hotels' => 31, 'season' => 'Nov - Apr', 'featured' => false, 'description' => 'Beaches, islands, and nightlife.', 'image' => 'https://images.unsplash.com/photo-1504214203695-9d9d0f4b0a56?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Bangkok Food & City Tour', 'location' => 'Bangkok', 'country' => 'Thailand', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$749', 'rating' => 4.6, 'hotels' => 29, 'season' => 'Nov - Feb', 'featured' => false, 'description' => 'Street food, malls, and temples.', 'image' => 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Singapore Urban Explorer', 'location' => 'Singapore', 'country' => 'Singapore', 'category' => 'City', 'duration' => '3 days', 'price_from' => '$699', 'rating' => 4.8, 'hotels' => 33, 'season' => 'Year-round', 'featured' => false, 'description' => 'Clean city breaks and family attractions.', 'image' => 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Tokyo Neon Discovery', 'location' => 'Tokyo', 'country' => 'Japan', 'category' => 'City', 'duration' => '7 days', 'price_from' => '$1,659', 'rating' => 4.9, 'hotels' => 45, 'season' => 'Year-round', 'featured' => true, 'description' => 'Anime, shopping, food, and iconic streets.', 'image' => 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Kyoto Cultural Route', 'location' => 'Kyoto', 'country' => 'Japan', 'category' => 'Culture', 'duration' => '5 days', 'price_from' => '$1,499', 'rating' => 4.9, 'hotels' => 27, 'season' => 'Year-round', 'featured' => false, 'description' => 'Temples, tea houses, and traditional lanes.', 'image' => 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Osaka Food Trail', 'location' => 'Osaka', 'country' => 'Japan', 'category' => 'Food', 'duration' => '4 days', 'price_from' => '$1,299', 'rating' => 4.8, 'hotels' => 25, 'season' => 'Year-round', 'featured' => false, 'description' => 'Street food, castles, and lively neighborhoods.', 'image' => 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Seoul Trendsetter Trip', 'location' => 'Seoul', 'country' => 'South Korea', 'category' => 'City', 'duration' => '5 days', 'price_from' => '$1,399', 'rating' => 4.8, 'hotels' => 30, 'season' => 'Year-round', 'featured' => false, 'description' => 'Fashion, cafes, and night markets.', 'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Jeju Island Calm', 'location' => 'Jeju', 'country' => 'South Korea', 'category' => 'Island', 'duration' => '4 days', 'price_from' => '$1,199', 'rating' => 4.7, 'hotels' => 19, 'season' => 'Year-round', 'featured' => false, 'description' => 'Volcanic coastlines and scenic drives.', 'image' => 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Paris Romantic Escape', 'location' => 'Paris', 'country' => 'France', 'category' => 'Romantic', 'duration' => '5 days', 'price_from' => '$1,899', 'rating' => 4.9, 'hotels' => 38, 'season' => 'Apr - Oct', 'featured' => true, 'description' => 'Museums, cafes, and classic landmarks.', 'image' => 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Nice Riviera Leisure', 'location' => 'Nice', 'country' => 'France', 'category' => 'Beach', 'duration' => '4 days', 'price_from' => '$1,699', 'rating' => 4.7, 'hotels' => 24, 'season' => 'May - Sep', 'featured' => false, 'description' => 'Coastal promenades and Mediterranean views.', 'image' => 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Rome Ancient Wonders', 'location' => 'Rome', 'country' => 'Italy', 'category' => 'Heritage', 'duration' => '5 days', 'price_from' => '$1,799', 'rating' => 4.9, 'hotels' => 36, 'season' => 'Apr - Oct', 'featured' => true, 'description' => 'Ruins, pasta, and timeless history.', 'image' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Venice Canal Journey', 'location' => 'Venice', 'country' => 'Italy', 'category' => 'Romantic', 'duration' => '4 days', 'price_from' => '$1,899', 'rating' => 4.8, 'hotels' => 21, 'season' => 'Apr - Oct', 'featured' => false, 'description' => 'Gondolas, bridges, and charming alleyways.', 'image' => 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Milan Style Weekend', 'location' => 'Milan', 'country' => 'Italy', 'category' => 'City', 'duration' => '3 days', 'price_from' => '$1,299', 'rating' => 4.6, 'hotels' => 18, 'season' => 'Year-round', 'featured' => false, 'description' => 'Fashion, design, and nightlife.', 'image' => 'https://images.unsplash.com/photo-1542044853-15e3b5b3d3f1?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Zurich Alpine Retreat', 'location' => 'Zurich', 'country' => 'Switzerland', 'category' => 'Luxury', 'duration' => '5 days', 'price_from' => '$2,299', 'rating' => 4.9, 'hotels' => 32, 'season' => 'Year-round', 'featured' => true, 'description' => 'Lakes, trains, and premium stays.', 'image' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Interlaken Adventure Base', 'location' => 'Interlaken', 'country' => 'Switzerland', 'category' => 'Adventure', 'duration' => '4 days', 'price_from' => '$2,099', 'rating' => 4.8, 'hotels' => 20, 'season' => 'Jun - Sep', 'featured' => false, 'description' => 'Paragliding, lakes, and mountains.', 'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Barcelona Coast & Culture', 'location' => 'Barcelona', 'country' => 'Spain', 'category' => 'City', 'duration' => '5 days', 'price_from' => '$1,749', 'rating' => 4.8, 'hotels' => 29, 'season' => 'Apr - Oct', 'featured' => true, 'description' => 'Architecture, beaches, and tapas.', 'image' => 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Madrid Art Circuit', 'location' => 'Madrid', 'country' => 'Spain', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.7, 'hotels' => 23, 'season' => 'Year-round', 'featured' => false, 'description' => 'Museums, plazas, and lively streets.', 'image' => 'https://images.unsplash.com/photo-1539037116277-4f312d3b3f9e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Lisbon Tram Trail', 'location' => 'Lisbon', 'country' => 'Portugal', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,499', 'rating' => 4.7, 'hotels' => 19, 'season' => 'Mar - Nov', 'featured' => false, 'description' => 'Hills, trams, and viewpoints.', 'image' => 'https://images.unsplash.com/photo-1513735492246-21a7b1bdf5d9?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Porto River Walk', 'location' => 'Porto', 'country' => 'Portugal', 'category' => 'Leisure', 'duration' => '3 days', 'price_from' => '$1,399', 'rating' => 4.6, 'hotels' => 16, 'season' => 'Apr - Oct', 'featured' => false, 'description' => 'Riverfront cafes and wine culture.', 'image' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Amsterdam Canal Loop', 'location' => 'Amsterdam', 'country' => 'Netherlands', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,699', 'rating' => 4.8, 'hotels' => 27, 'season' => 'Apr - Sep', 'featured' => false, 'description' => 'Canals, bikes, and museums.', 'image' => 'https://images.unsplash.com/photo-1489493543158-3f94d8a3d0e1?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Prague Old Town Escape', 'location' => 'Prague', 'country' => 'Czech Republic', 'category' => 'Heritage', 'duration' => '4 days', 'price_from' => '$1,299', 'rating' => 4.8, 'hotels' => 20, 'season' => 'Apr - Oct', 'featured' => false, 'description' => 'Castles, cobblestones, and skyline views.', 'image' => 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Vienna Classical Tour', 'location' => 'Vienna', 'country' => 'Austria', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.7, 'hotels' => 21, 'season' => 'Year-round', 'featured' => false, 'description' => 'Palaces, coffeehouses, and music.', 'image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'London Landmark Highlights', 'location' => 'London', 'country' => 'UK', 'category' => 'City', 'duration' => '5 days', 'price_from' => '$1,899', 'rating' => 4.8, 'hotels' => 34, 'season' => 'Year-round', 'featured' => false, 'description' => 'Museums, parks, and iconic sights.', 'image' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Edinburgh Castle Trail', 'location' => 'Edinburgh', 'country' => 'UK', 'category' => 'Heritage', 'duration' => '4 days', 'price_from' => '$1,649', 'rating' => 4.7, 'hotels' => 18, 'season' => 'May - Sep', 'featured' => false, 'description' => 'Historic lanes and castle views.', 'image' => 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'New York City Sprint', 'location' => 'New York', 'country' => 'USA', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,999', 'rating' => 4.9, 'hotels' => 41, 'season' => 'Year-round', 'featured' => true, 'description' => 'Skyscrapers, shopping, and Broadway.', 'image' => 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Los Angeles Coast Drive', 'location' => 'Los Angeles', 'country' => 'USA', 'category' => 'Leisure', 'duration' => '5 days', 'price_from' => '$1,899', 'rating' => 4.6, 'hotels' => 29, 'season' => 'Year-round', 'featured' => false, 'description' => 'Beach drives, studios, and sunsets.', 'image' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'San Francisco Bay Explorer', 'location' => 'San Francisco', 'country' => 'USA', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,799', 'rating' => 4.7, 'hotels' => 26, 'season' => 'Year-round', 'featured' => false, 'description' => 'Bridges, cafes, and bay views.', 'image' => 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Las Vegas Weekend Rush', 'location' => 'Las Vegas', 'country' => 'USA', 'category' => 'Entertainment', 'duration' => '3 days', 'price_from' => '$1,499', 'rating' => 4.5, 'hotels' => 22, 'season' => 'Year-round', 'featured' => false, 'description' => 'Shows, nightlife, and casino energy.', 'image' => 'https://images.unsplash.com/photo-1513866945341-4b27b7da8c8f?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Hawaii Island Retreat', 'location' => 'Maui', 'country' => 'USA', 'category' => 'Beach', 'duration' => '6 days', 'price_from' => '$2,499', 'rating' => 4.9, 'hotels' => 37, 'season' => 'Year-round', 'featured' => true, 'description' => 'Tropical beaches and volcanic scenery.', 'image' => 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Vancouver Nature & City', 'location' => 'Vancouver', 'country' => 'Canada', 'category' => 'Nature', 'duration' => '5 days', 'price_from' => '$1,899', 'rating' => 4.8, 'hotels' => 28, 'season' => 'Year-round', 'featured' => false, 'description' => 'Mountains, waterfront, and food.', 'image' => 'https://images.unsplash.com/photo-1502717388385-4c5f1cfe4b68?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Banff Alpine Escape', 'location' => 'Banff', 'country' => 'Canada', 'category' => 'Adventure', 'duration' => '5 days', 'price_from' => '$2,199', 'rating' => 4.9, 'hotels' => 24, 'season' => 'Jun - Sep', 'featured' => true, 'description' => 'Lakes, hikes, and scenic drives.', 'image' => 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Toronto City Mix', 'location' => 'Toronto', 'country' => 'Canada', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.6, 'hotels' => 20, 'season' => 'Year-round', 'featured' => false, 'description' => 'Museums, towers, and diverse food.', 'image' => 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Montreal French Charm', 'location' => 'Montreal', 'country' => 'Canada', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$1,499', 'rating' => 4.7, 'hotels' => 18, 'season' => 'May - Oct', 'featured' => false, 'description' => 'Old town, cafes, and festivals.', 'image' => 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=900&q=80'],

            ['title' => 'Cape Town Scenic Loop', 'location' => 'Cape Town', 'country' => 'South Africa', 'category' => 'Nature', 'duration' => '6 days', 'price_from' => '$1,799', 'rating' => 4.9, 'hotels' => 30, 'season' => 'Year-round', 'featured' => true, 'description' => 'Mountains, beaches, and wine routes.', 'image' => 'https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Kruger Safari Classic', 'location' => 'Kruger', 'country' => 'South Africa', 'category' => 'Wildlife', 'duration' => '5 days', 'price_from' => '$2,299', 'rating' => 4.9, 'hotels' => 28, 'season' => 'May - Sep', 'featured' => true, 'description' => 'Big Five safaris and lodge stays.', 'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Nairobi Safari Gateway', 'location' => 'Nairobi', 'country' => 'Kenya', 'category' => 'Wildlife', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.8, 'hotels' => 21, 'season' => 'Year-round', 'featured' => false, 'description' => 'Safari access and city energy.', 'image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Maasai Mara Wildlife Trip', 'location' => 'Maasai Mara', 'country' => 'Kenya', 'category' => 'Wildlife', 'duration' => '5 days', 'price_from' => '$1,899', 'rating' => 4.9, 'hotels' => 25, 'season' => 'Jul - Oct', 'featured' => true, 'description' => 'Game drives and iconic savannahs.', 'image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Marrakech Color Walk', 'location' => 'Marrakech', 'country' => 'Morocco', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$1,299', 'rating' => 4.7, 'hotels' => 19, 'season' => 'Oct - Apr', 'featured' => false, 'description' => 'Souks, gardens, and riads.', 'image' => 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Casablanca Coastal City', 'location' => 'Casablanca', 'country' => 'Morocco', 'category' => 'City', 'duration' => '3 days', 'price_from' => '$1,149', 'rating' => 4.5, 'hotels' => 15, 'season' => 'Oct - Apr', 'featured' => false, 'description' => 'Oceanfront, cafes, and city vibes.', 'image' => 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Reykjavik Northern Lights', 'location' => 'Reykjavik', 'country' => 'Iceland', 'category' => 'Nature', 'duration' => '5 days', 'price_from' => '$2,599', 'rating' => 4.9, 'hotels' => 17, 'season' => 'Oct - Mar', 'featured' => true, 'description' => 'Geothermal spas and aurora hunts.', 'image' => 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Blue Lagoon Wellness', 'location' => 'Reykjavik', 'country' => 'Iceland', 'category' => 'Wellness', 'duration' => '4 days', 'price_from' => '$2,399', 'rating' => 4.8, 'hotels' => 14, 'season' => 'Year-round', 'featured' => false, 'description' => 'Relaxing spa-focused escape.', 'image' => 'https://images.unsplash.com/photo-1500043357865-c6b8827edf4e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Sydney Harbour Highlights', 'location' => 'Sydney', 'country' => 'Australia', 'category' => 'City', 'duration' => '5 days', 'price_from' => '$2,099', 'rating' => 4.8, 'hotels' => 33, 'season' => 'Year-round', 'featured' => false, 'description' => 'Harbour views, beaches, and landmarks.', 'image' => 'https://images.unsplash.com/photo-1506973035872-a4d9c7f6d7af?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Melbourne Coffee & Art', 'location' => 'Melbourne', 'country' => 'Australia', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,899', 'rating' => 4.7, 'hotels' => 25, 'season' => 'Year-round', 'featured' => false, 'description' => 'Laneways, art, and cafe culture.', 'image' => 'https://images.unsplash.com/photo-1506038634487-60a69ae4b7b0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Gold Coast Surf Break', 'location' => 'Gold Coast', 'country' => 'Australia', 'category' => 'Beach', 'duration' => '4 days', 'price_from' => '$1,999', 'rating' => 4.6, 'hotels' => 23, 'season' => 'Year-round', 'featured' => false, 'description' => 'Surf, sunshine, and coastlines.', 'image' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Auckland Island Hop', 'location' => 'Auckland', 'country' => 'New Zealand', 'category' => 'Nature', 'duration' => '5 days', 'price_from' => '$2,099', 'rating' => 4.8, 'hotels' => 19, 'season' => 'Year-round', 'featured' => false, 'description' => 'Harbors, islands, and scenic drives.', 'image' => 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Queenstown Adventure Rush', 'location' => 'Queenstown', 'country' => 'New Zealand', 'category' => 'Adventure', 'duration' => '5 days', 'price_from' => '$2,299', 'rating' => 4.9, 'hotels' => 24, 'season' => 'Year-round', 'featured' => true, 'description' => 'Bungee, lakes, and mountain thrills.', 'image' => 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Rio Carnival Style Trip', 'location' => 'Rio de Janeiro', 'country' => 'Brazil', 'category' => 'Festival', 'duration' => '5 days', 'price_from' => '$1,799', 'rating' => 4.8, 'hotels' => 27, 'season' => 'Dec - Mar', 'featured' => false, 'description' => 'Beaches, music, and city energy.', 'image' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'São Paulo Urban Mix', 'location' => 'São Paulo', 'country' => 'Brazil', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.5, 'hotels' => 18, 'season' => 'Year-round', 'featured' => false, 'description' => 'Food, nightlife, and modern city life.', 'image' => 'https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Buenos Aires Tango Trail', 'location' => 'Buenos Aires', 'country' => 'Argentina', 'category' => 'Culture', 'duration' => '5 days', 'price_from' => '$1,699', 'rating' => 4.7, 'hotels' => 20, 'season' => 'Mar - May', 'featured' => false, 'description' => 'Tango, steak, and European-inspired streets.', 'image' => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Mendoza Wine Escape', 'location' => 'Mendoza', 'country' => 'Argentina', 'category' => 'Leisure', 'duration' => '4 days', 'price_from' => '$1,549', 'rating' => 4.8, 'hotels' => 16, 'season' => 'Mar - May', 'featured' => false, 'description' => 'Vineyards and mountain views.', 'image' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Santiago City & Andes', 'location' => 'Santiago', 'country' => 'Chile', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$1,599', 'rating' => 4.6, 'hotels' => 19, 'season' => 'Year-round', 'featured' => false, 'description' => 'Urban stays with mountain day trips.', 'image' => 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Cusco Inca Heritage', 'location' => 'Cusco', 'country' => 'Peru', 'category' => 'Heritage', 'duration' => '5 days', 'price_from' => '$1,799', 'rating' => 4.9, 'hotels' => 22, 'season' => 'May - Oct', 'featured' => true, 'description' => 'Andean culture and historic ruins.', 'image' => 'https://images.unsplash.com/photo-1516306537076-4d7b4c0b1b7c?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Machu Picchu Classic', 'location' => 'Aguas Calientes', 'country' => 'Peru', 'category' => 'Adventure', 'duration' => '6 days', 'price_from' => '$1,999', 'rating' => 4.9, 'hotels' => 30, 'season' => 'May - Oct', 'featured' => true, 'description' => 'Bucket-list trek and iconic views.', 'image' => 'https://images.unsplash.com/photo-1516107446439-8e6d5c7f9f2f?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Hanoi Old Quarter Walk', 'location' => 'Hanoi', 'country' => 'Vietnam', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$999', 'rating' => 4.7, 'hotels' => 26, 'season' => 'Oct - Apr', 'featured' => false, 'description' => 'Street food, history, and lakes.', 'image' => 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Ha Long Bay Cruise', 'location' => 'Ha Long Bay', 'country' => 'Vietnam', 'category' => 'Nature', 'duration' => '3 days', 'price_from' => '$1,099', 'rating' => 4.8, 'hotels' => 24, 'season' => 'Oct - Apr', 'featured' => true, 'description' => 'Cruise, caves, and limestone cliffs.', 'image' => 'https://images.unsplash.com/photo-1505968409348-bd000797c92e?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Ho Chi Minh City Sprint', 'location' => 'Ho Chi Minh City', 'country' => 'Vietnam', 'category' => 'City', 'duration' => '4 days', 'price_from' => '$949', 'rating' => 4.6, 'hotels' => 21, 'season' => 'Year-round', 'featured' => false, 'description' => 'Markets, cafes, and fast-paced city life.', 'image' => 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Siem Reap Temple Trail', 'location' => 'Siem Reap', 'country' => 'Cambodia', 'category' => 'Heritage', 'duration' => '4 days', 'price_from' => '$1,149', 'rating' => 4.8, 'hotels' => 18, 'season' => 'Nov - Mar', 'featured' => false, 'description' => 'Temples, culture, and sunrise views.', 'image' => 'https://images.unsplash.com/photo-1504626835342-26e8f1bd2f9a?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Luang Prabang Calm', 'location' => 'Luang Prabang', 'country' => 'Laos', 'category' => 'Leisure', 'duration' => '4 days', 'price_from' => '$1,049', 'rating' => 4.7, 'hotels' => 14, 'season' => 'Nov - Mar', 'featured' => false, 'description' => 'River life, temples, and slow travel.', 'image' => 'https://images.unsplash.com/photo-1496535231037-209fc76c86f5?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Kathmandu Valley Explorer', 'location' => 'Kathmandu', 'country' => 'Nepal', 'category' => 'Culture', 'duration' => '4 days', 'price_from' => '$899', 'rating' => 4.7, 'hotels' => 20, 'season' => 'Year-round', 'featured' => false, 'description' => 'Heritage sites and Himalayan gateway.', 'image' => 'https://images.unsplash.com/photo-1558383331-13f0d6d0f2f0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Pokhara Lakeside Reset', 'location' => 'Pokhara', 'country' => 'Nepal', 'category' => 'Nature', 'duration' => '5 days', 'price_from' => '$999', 'rating' => 4.8, 'hotels' => 16, 'season' => 'Year-round', 'featured' => false, 'description' => 'Lakes, paragliding, and mountain views.', 'image' => 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Doha City Stopover', 'location' => 'Doha', 'country' => 'Qatar', 'category' => 'City', 'duration' => '3 days', 'price_from' => '$899', 'rating' => 4.6, 'hotels' => 18, 'season' => 'Nov - Mar', 'featured' => false, 'description' => 'Modern skyline and desert experiences.', 'image' => 'https://images.unsplash.com/photo-1501117716987-c8e1ecb210c0?auto=format&fit=crop&w=900&q=80'],
            ['title' => 'Muscat Coastline Escape', 'location' => 'Muscat', 'country' => 'Oman', 'category' => 'Leisure', 'duration' => '4 days', 'price_from' => '$1,199', 'rating' => 4.7, 'hotels' => 17, 'season' => 'Oct - Apr', 'featured' => false, 'description' => 'Coastlines, forts, and calm luxury.', 'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80'],
        ];

        foreach ($exploreItems as $index => $item) {
            $item['image'] = ExploreItem::imageUrlFor(
                $item['title'],
                $item['location'],
                $item['country'],
                $item['category'],
                $index
            );

            ExploreItem::updateOrCreate(
                [
                    'title' => $item['title'],
                    'location' => $item['location'],
                    'country' => $item['country'],
                ],
                $item
            );
        }
    }
}
